# Generated by Django 3.0.4 on 2020-04-25 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_id', models.BigIntegerField(null=True, verbose_name='Внешний код для Api')),
                ('customer_bin', models.CharField(max_length=255, null=True, verbose_name='Бин организатора')),
                ('totalLots', models.FloatField(null=True, verbose_name='Кол-во лотов в объявлении')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Наименование лота')),
                ('itemZakup', models.CharField(max_length=255, null=True, verbose_name='Предмет закупки')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Место поставки')),
                ('addressFull', models.CharField(max_length=255, null=True, verbose_name='Место постаки, полный адресс')),
                ('body', models.CharField(max_length=255, null=True, verbose_name='Заказчик:')),
                ('numb', models.CharField(max_length=150, null=True, verbose_name='Номер лота')),
                ('price', models.FloatField(null=True, verbose_name='Цена')),
                ('statzakup', models.CharField(choices=[('draft', 'Запрос ценовых предложении'), ('win', 'Конкурс'), ('sended', 'Аукцион')], default='draft', max_length=10, verbose_name='Способ закупки')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата закрытия:')),
                ('date_open', models.DateTimeField(null=True, verbose_name='Дата открытия:')),
                ('yst', models.URLField(max_length=255, null=True, verbose_name='Ссылка')),
                ('sign_reason_doc_name', models.CharField(max_length=255, null=True, verbose_name='Наименование подтверждающего документа')),
                ('down', models.FileField(null=True, upload_to='media/', verbose_name='Документы для загрузки')),
                ('status', models.BooleanField(db_index=True, default=True, null=True, verbose_name='Опубликован')),
                ('slug', models.SlugField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lots.Cities', verbose_name='Город')),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
            },
        ),
    ]
