# Generated by Django 3.0.4 on 2020-06-25 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 19, 30, 22, 118624, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
