# Generated by Django 3.0.4 on 2020-08-15 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 15, 41, 55, 612781, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
