# Generated by Django 3.0.4 on 2020-04-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='purchase_method',
            field=models.CharField(max_length=255, null=True, verbose_name='Purchase Method'),
        ),
    ]
