# Generated by Django 3.0.4 on 2020-07-01 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_article_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 5, 33, 25, 620544, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
