# Generated by Django 3.0.4 on 2020-08-16 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_auto_20200816_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 13, 32, 7, 452239, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
