# Generated by Django 3.0.4 on 2020-07-01 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auto_20200701_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 11, 5, 44, 598266, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
