# Generated by Django 3.0.4 on 2020-08-16 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auto_20200816_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 16, 13, 54, 20296, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
