# Generated by Django 3.0.4 on 2020-05-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auto_20200503_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.PROTECT, to='lots.Cities', verbose_name='Город'),
        ),
    ]
