# Generated by Django 3.0.4 on 2020-07-01 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_auto_20200701_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 11, 33, 28, 893187, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
