# Generated by Django 3.0.4 on 2020-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_auto_20200517_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='xml_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Внешний код для Api'),
        ),
    ]
