# Generated by Django 3.0.4 on 2020-08-16 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_auto_20200816_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 16, 35, 9, 247979, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
