# Generated by Django 3.0.4 on 2020-08-18 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_auto_20200816_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 15, 7, 37, 638664, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
