# Generated by Django 3.0.4 on 2020-05-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_auto_20200517_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='address',
        ),
    ]
