# Generated by Django 3.0.4 on 2020-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0007_remove_article_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Место поставки'),
        ),
    ]
