# Generated by Django 3.0.4 on 2020-05-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0008_article_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='address',
        ),
    ]
