# Generated by Django 3.0.4 on 2020-05-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_remove_article_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
