# Generated by Django 3.0.4 on 2020-08-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_auto_20200823_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='statzakup',
            field=models.CharField(choices=[('Запрос ценовых предложений', 'Запрос ценовых предложений'), ('Конкурс', 'Конкурс'), ('Аукцион', 'Аукцион')], default='Аукцион', max_length=255, verbose_name='Способ закупки'),
        ),
    ]
