# Generated by Django 3.0.4 on 2020-05-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_auto_20200519_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='totalLots',
        ),
    ]
