# Generated by Django 3.0.4 on 2020-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_auto_20200825_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='itemZakup',
            field=models.CharField(choices=[('product', 'Товар'), ('services', 'Услуга'), ('job', 'Работа')], default='product', max_length=255, verbose_name='Предмет закупки'),
        ),
    ]
