# Generated by Django 3.0.4 on 2020-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0011_remove_article_totallots'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lotFullName',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя лота'),
        ),
    ]
