# Generated by Django 3.0.4 on 2020-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0012_article_lotfullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20, null=True, verbose_name='Цена'),
        ),
    ]
