# Generated by Django 3.0.4 on 2020-05-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0013_auto_20200524_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='code',
            field=models.CharField(default=-1, max_length=30, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lots.Cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
    ]
