# Generated by Django 3.0.4 on 2020-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0014_auto_20200525_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=30, verbose_name='Код')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'районы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='cities',
            name='code',
            field=models.CharField(default=None, max_length=30, verbose_name='Код'),
        ),
    ]
