# Generated by Django 3.0.4 on 2020-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0015_article_date_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата закрытия:'),
        ),
    ]
