# Generated by Django 3.0.4 on 2020-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0016_auto_20200405_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата закрытия:'),
        ),
    ]
