# Generated by Django 3.0.4 on 2020-05-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0016_article_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sign_reason_doc_name',
        ),
    ]
