# Generated by Django 3.0.4 on 2020-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0017_auto_20200405_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_only',
            field=models.DateField(null=True, verbose_name='Дата закрытия (date):'),
        ),
    ]
