# Generated by Django 3.0.4 on 2020-04-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0018_article_date_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_only',
        ),
    ]
