# Generated by Django 3.0.4 on 2020-05-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0019_lotfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='down',
        ),
    ]
