# Generated by Django 3.0.4 on 2020-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0021_article_purchase_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='purchase_method',
        ),
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Место поставки'),
        ),
        migrations.AddField(
            model_name='article',
            name='addressFull',
            field=models.CharField(max_length=255, null=True, verbose_name='Место постаки, полный адресс'),
        ),
        migrations.AddField(
            model_name='article',
            name='customer_bin',
            field=models.CharField(max_length=255, null=True, verbose_name='Бин организатора'),
        ),
        migrations.AddField(
            model_name='article',
            name='itemZakup',
            field=models.CharField(max_length=255, null=True, verbose_name='Предмет закупки'),
        ),
        migrations.AddField(
            model_name='article',
            name='sign_reason_doc_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование подтверждающего документа'),
        ),
        migrations.AddField(
            model_name='article',
            name='totalLots',
            field=models.FloatField(null=True, verbose_name='Кол-во лотов в объявлении'),
        ),
        migrations.AddField(
            model_name='article',
            name='xml_id',
            field=models.BigIntegerField(null=True, verbose_name='Внешний код для Api'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=255, null=True, verbose_name='Заказчик:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=True, null=True, verbose_name='Дата закрытия:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_open',
            field=models.DateTimeField(default=True, null=True, verbose_name='Дата открытия:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(db_index=True, default=True, null=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование лота'),
        ),
    ]
