# Generated by Django 3.0.4 on 2020-08-01 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField(auto_now_add=True, null=True)),
                ('rassylka', models.BooleanField(default=True, verbose_name='Подписаться на email рассылку')),
                ('tarif', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Price', verbose_name='Тариф')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
