# Generated by Django 3.0.4 on 2020-08-16 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarif',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Price', verbose_name='Тариф'),
        ),
    ]
