# Generated by Django 3.0.4 on 2020-06-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200617_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarif',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='users.Price', verbose_name='Тариф'),
        ),
    ]
