# Generated by Django 3.0.4 on 2020-07-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200619_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarif',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Price', verbose_name='Тариф'),
        ),
    ]
