# Generated by Django 3.0.4 on 2020-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200823_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_business_number',
            field=models.CharField(max_length=30, null=True, verbose_name='ИИН/БИН'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Наименование компании'),
        ),
    ]
