# Generated by Django 3.0.4 on 2020-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201003_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tarif_start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(choices=[('MN12', 'Клиент - на 12 месяцев'), ('MN6', 'Клиент - на 6 месяцев'), ('MN3', 'Клиент - на 3 месяца'), ('MN1', 'Клиент - на 1 месяц'), ('EXP_MN12', 'Эксперт - на 12 месяцев'), ('EXP_MN6', 'Эксперт - на 6 месяцев'), ('EXP_MN3', 'Эксперт - на 3 месяца'), ('EXP_MN1', 'Эксперт - на 1 месяц')], db_index=True, default='MN1', max_length=30, verbose_name='Название'),
        ),
    ]
