# Generated by Django 3.0.4 on 2020-10-04 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201004_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tarif_start_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='tarif_expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 15, 17, 30, 173372), null=True),
        ),
    ]
