# Generated by Django 3.0.4 on 2020-10-04 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201004_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarif_expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 9, 20, 32, 722302, tzinfo=utc), null=True),
        ),
    ]
