# Generated by Django 3.0.4 on 2020-10-04 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201004_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarif_expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 9, 24, 43, 620147, tzinfo=utc), null=True),
        ),
    ]
