# Generated by Django 3.0.4 on 2020-10-04 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201004_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarif_expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 15, 17, 58, 752031, tzinfo=utc), null=True),
        ),
    ]
