# Generated by Django 3.0.4 on 2021-02-11 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201004_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarif_expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 11, 11, 57, 2, 370191, tzinfo=utc), null=True),
        ),
    ]
