#!/bin/bash 

NAME="tn_first"                                 # Name of the application 
DJANGODIR=/webapps/django_shop/tendernet            # Django project directory 
SOCKFILE=unix:/webapps/django_shop/tendernet/tendernet.sock # we will communicte using this unix socket 
USER=root                                       # the user to run as 
GROUP=root                                    # the group to run as 
NUM_WORKERS=3                                    # how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=tn_first.settings            # which settings file should Django use 
DJANGO_WSGI_MODULE=tn_first.wsgi                    # WSGI module name 

echo "Starting $NAME as `whoami`" 

# Activate the virtual environment 
#cd $DJANGODIR 
source  /webapps/django_shop/django_env/bin/activate
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE 
export PYTHONPATH=$DJANGODIR:$PYTHONPATH 

# Create the run directory if it doesn't exist 
#RUNDIR=$(dirname $SOCKFILE) 
#test -d $RUNDIR || mkdir -p $RUNDIR 

# Start your Django Unicorn 
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon) 
exec /webapps/django_shop/django_env/bin/gunicorn --access-logfile /webapps/django_shop/tendernet/app.log --capture-output --enable-stdio-inheritance ${DJANGO_WSGI_MODULE}:application \ 
 --name $NAME \ 
 --workers $NUM_WORKERS \ 
 --user=$USER --group=$GROUP \ 
 --bind=$SOCKFILE \ 
# --bind=localhost:8000
 --log-level=debug \ 
 --log-file=/webapps/django_shop/tendernet/app.log
