# Generated by Django 3.0.4 on 2020-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='expert_preference',
            field=models.TextField(default='', verbose_name='Expert Preference'),
        ),
    ]
