# Generated by Django 3.0.4 on 2020-06-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='status',
            field=models.CharField(choices=[('draft', ''), ('win', 'В обработке'), ('send', 'Подача заявки'), ('sended', 'Обработан')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='zakazdoc',
            name='status',
            field=models.CharField(choices=[('draft', ''), ('win', 'Выигрыш'), ('sended', 'Заявка отправлено')], default='draft', max_length=10),
        ),
    ]
