# Generated by Django 3.0.4 on 2021-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0002_zakaz_expert_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='expert_preference',
            field=models.TextField(default='{}', verbose_name='Expert Preference'),
        ),
    ]
